name = "dishify-api"
compatibility_date = "2023-10-30"
send_metrics = true
main = "src/worker.ts"
account_id = "8ec43c4425032808531ab8274abee3d8"

tail_consumers = [{service = "dishify-api-tail"}]

# [[d1_databases]]
# binding = "DB"
# database_name = "production"
# database_id = ""
# migrations_dir = "migrations"

[[d1_databases]]
binding = "DB"
database_name = "dishify_preview"
database_id = "2ebfeb64-c519-4be1-af5c-a117464635dd"
migrations_dir = "migrations"

[ai]
binding = "AI"