name = "dishify"
main = ".worker-next/index.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "81584d35b7a146cab34cdd01d354f8dd"