import { vars } from "nativewind";

export const themes = {
  default: {
    light: vars({
      "--background": "#ffffff",
      "--foreground": "#020817",
      "--primary": "#000000",
      "--primary-foreground": "#f8fafc",
      "--secondary": "#7d7d7d",
      "--secondary-foreground": "#f8fafc",
      "--tertiary": "#f0f2f5",
      "--tertiary-foreground": "#0f172a",
      "--muted": "#f1f5f9",
      "--muted-foreground": "	#64748b",
      "--accent": "#f1f5f9",
      "--accent-foreground": "#0f172a",
      "--destructive": "#ef4444",
      "--destructive-foreground": "#f8fafc",
      "--border": "#e2e8f0",
      "--input": "#e2e8f0",
      "--ring": "#cccccc",
      "--popover": "#ffffff",
      "--popover-foreground": "#020817",
      "--card": "#ffffff",
      "--card-foreground": "#020817",
    }),
    dark: vars({
      "--background": "#09090b",
      "--foreground": "#fafafa",
      "--primary": "#fafafa",
      "--primary-foreground": "#18181b",
      "--secondary": "#27272a",
      "--secondary-foreground": "#fafafa",
      "--tertiary": "#000000",
      "--tertiary-foreground": "#0f172a",
      "--muted": "#27272a",
      "--muted-foreground": "#a1a1aa",
      "--accent": "#27272a",
      "--accent-foreground": "#fafafa",
      "--destructive": "#7f1d1d",
      "--destructive-foreground": "#fafafa",
      "--border": "#27272a",
      "--input": "#27272a",
      "--ring": "#d4d4d8",
      "--popover": "#09090b",
      "--popover-foreground": "#fafafa",
      "--card": "#09090b",
      "--card-foreground": "#fafafa",
    }),
  },
  christmas: {
    light: vars({
      "--primary": "0 100% 50%",
      "--secondary": "115 100% 50%",
    }),
    dark: vars({
      "--primary": "115 100% 50%",
      "--secondary": "0 100% 50%",
    }),
  },
};
