import "../global.css";
import { Provider } from "app/provider";
import { Provider as JotAIProvider } from "jotai";

export const metadata = {
  title: "Create Solito App",
  description: "Generated by create Solito app",
};

export default function Layout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <JotAIProvider>
          <Provider initialSession={null}>{props.children}</Provider>
        </JotAIProvider>
      </body>
    </html>
  );
}
