name: 'Next.js Deployment'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/next/**'
      - 'packages/ui/**'
      - 'packages/app/**'

jobs:
  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Bun setup'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 'Bun install'
        run: bun install

      - name: Build
        run: |
          cd apps/next
          export NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          export NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}
          export NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          export NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          bunx @cloudflare/next-on-pages

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: .vercel/output/static
          branch: main
          wranglerVersion: '3'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: apps/next
